/**
* Generated by Kubb (https://kubb.dev/).
* Do not edit manually.
*/

import fetch from "@/lib/authorized-client";
import type { RequestConfig, ResponseErrorConfig } from "@/lib/authorized-client";
import type { QueryKey, QueryClient, QueryObserverOptions, UseQueryResult } from "@tanstack/react-query";
import type { GetMetadataMetadataGetQueryResponse } from "../types/GetMetadataMetadataGet";
import { queryOptions, useQuery } from "@tanstack/react-query";

export const getMetadataMetadataGetQueryKey = () => [{ url: '/metadata' }] as const

export type GetMetadataMetadataGetQueryKey = ReturnType<typeof getMetadataMetadataGetQueryKey>

/**
 * @summary Get Metadata
 * {@link /metadata}
 */
export async function getMetadataMetadataGet(config: Partial<RequestConfig> & { client?: typeof fetch } = {}) {
  const { client: request = fetch, ...requestConfig } = config  
  
  const res = await request<GetMetadataMetadataGetQueryResponse, ResponseErrorConfig<Error>, unknown>({ method : "GET", url : `/metadata`, ... requestConfig })  
  return res.data
}

export function getMetadataMetadataGetQueryOptions(config: Partial<RequestConfig> & { client?: typeof fetch } = {}) {
  const queryKey = getMetadataMetadataGetQueryKey()
  return queryOptions<GetMetadataMetadataGetQueryResponse, ResponseErrorConfig<Error>, GetMetadataMetadataGetQueryResponse, typeof queryKey>({
 
   queryKey,
   queryFn: async ({ signal }) => {
      config.signal = signal
      return getMetadataMetadataGet(config)
   },
  })
}

/**
 * @summary Get Metadata
 * {@link /metadata}
 */
export function useGetMetadataMetadataGet<TData = GetMetadataMetadataGetQueryResponse, TQueryData = GetMetadataMetadataGetQueryResponse, TQueryKey extends QueryKey = GetMetadataMetadataGetQueryKey>(options: 
{
  query?: Partial<QueryObserverOptions<GetMetadataMetadataGetQueryResponse, ResponseErrorConfig<Error>, TData, TQueryData, TQueryKey>> & { client?: QueryClient },
  client?: Partial<RequestConfig> & { client?: typeof fetch }
}
 = {}) {
  const { query: queryConfig = {}, client: config = {} } = options ?? {}
  const { client: queryClient, ...queryOptions } = queryConfig
  const queryKey = queryOptions?.queryKey ?? getMetadataMetadataGetQueryKey()

  const query = useQuery({
   ...getMetadataMetadataGetQueryOptions(config),
   queryKey,
   ...queryOptions
  } as unknown as QueryObserverOptions, queryClient) as UseQueryResult<TData, ResponseErrorConfig<Error>> & { queryKey: TQueryKey }

  query.queryKey = queryKey as TQueryKey

  return query
}