/**
* Generated by Kubb (https://kubb.dev/).
* Do not edit manually.
*/

import fetch from "@/lib/authorized-client";
import type { RequestConfig, ResponseErrorConfig } from "@/lib/authorized-client";
import type { QueryKey, QueryClient, UseSuspenseQueryOptions, UseSuspenseQueryResult } from "@tanstack/react-query";
import type { GetConfigApiConfigGetQueryResponse } from "../types/GetConfigApiConfigGet";
import { queryOptions, useSuspenseQuery } from "@tanstack/react-query";

export const getConfigApiConfigGetSuspenseQueryKey = () => [{ url: '/api/config' }] as const

export type GetConfigApiConfigGetSuspenseQueryKey = ReturnType<typeof getConfigApiConfigGetSuspenseQueryKey>

/**
 * @summary Get Config
 * {@link /api/config}
 */
export async function getConfigApiConfigGetSuspense(config: Partial<RequestConfig> & { client?: typeof fetch } = {}) {
  const { client: request = fetch, ...requestConfig } = config  
  
  const res = await request<GetConfigApiConfigGetQueryResponse, ResponseErrorConfig<Error>, unknown>({ method : "GET", url : `/api/config`, ... requestConfig })  
  return res.data
}

export function getConfigApiConfigGetSuspenseQueryOptions(config: Partial<RequestConfig> & { client?: typeof fetch } = {}) {
  const queryKey = getConfigApiConfigGetSuspenseQueryKey()
  return queryOptions<GetConfigApiConfigGetQueryResponse, ResponseErrorConfig<Error>, GetConfigApiConfigGetQueryResponse, typeof queryKey>({
 
   queryKey,
   queryFn: async ({ signal }) => {
      config.signal = signal
      return getConfigApiConfigGetSuspense(config)
   },
  })
}

/**
 * @summary Get Config
 * {@link /api/config}
 */
export function useGetConfigApiConfigGetSuspense<TData = GetConfigApiConfigGetQueryResponse, TQueryKey extends QueryKey = GetConfigApiConfigGetSuspenseQueryKey>(options: 
{
  query?: Partial<UseSuspenseQueryOptions<GetConfigApiConfigGetQueryResponse, ResponseErrorConfig<Error>, TData, TQueryKey>> & { client?: QueryClient },
  client?: Partial<RequestConfig> & { client?: typeof fetch }
}
 = {}) {
  const { query: queryConfig = {}, client: config = {} } = options ?? {}
  const { client: queryClient, ...queryOptions } = queryConfig
  const queryKey = queryOptions?.queryKey ?? getConfigApiConfigGetSuspenseQueryKey()

  const query = useSuspenseQuery({
   ...getConfigApiConfigGetSuspenseQueryOptions(config),
   queryKey,
   ...queryOptions
  } as unknown as UseSuspenseQueryOptions, queryClient) as UseSuspenseQueryResult<TData, ResponseErrorConfig<Error>> & { queryKey: TQueryKey }

  query.queryKey = queryKey as TQueryKey

  return query
}