/**
* Generated by Kubb (https://kubb.dev/).
* Do not edit manually.
*/

import fetch from "@/lib/authorized-client";
import type { RequestConfig, ResponseErrorConfig } from "@/lib/authorized-client";
import type { QueryKey, QueryClient, UseSuspenseQueryOptions, UseSuspenseQueryResult } from "@tanstack/react-query";
import type { GetMetadataMetadataGetQueryResponse } from "../types/GetMetadataMetadataGet";
import { queryOptions, useSuspenseQuery } from "@tanstack/react-query";

export const getMetadataMetadataGetSuspenseQueryKey = () => [{ url: '/metadata' }] as const

export type GetMetadataMetadataGetSuspenseQueryKey = ReturnType<typeof getMetadataMetadataGetSuspenseQueryKey>

/**
 * @summary Get Metadata
 * {@link /metadata}
 */
export async function getMetadataMetadataGetSuspense(config: Partial<RequestConfig> & { client?: typeof fetch } = {}) {
  const { client: request = fetch, ...requestConfig } = config  
  
  const res = await request<GetMetadataMetadataGetQueryResponse, ResponseErrorConfig<Error>, unknown>({ method : "GET", url : `/metadata`, ... requestConfig })  
  return res.data
}

export function getMetadataMetadataGetSuspenseQueryOptions(config: Partial<RequestConfig> & { client?: typeof fetch } = {}) {
  const queryKey = getMetadataMetadataGetSuspenseQueryKey()
  return queryOptions<GetMetadataMetadataGetQueryResponse, ResponseErrorConfig<Error>, GetMetadataMetadataGetQueryResponse, typeof queryKey>({
 
   queryKey,
   queryFn: async ({ signal }) => {
      config.signal = signal
      return getMetadataMetadataGetSuspense(config)
   },
  })
}

/**
 * @summary Get Metadata
 * {@link /metadata}
 */
export function useGetMetadataMetadataGetSuspense<TData = GetMetadataMetadataGetQueryResponse, TQueryKey extends QueryKey = GetMetadataMetadataGetSuspenseQueryKey>(options: 
{
  query?: Partial<UseSuspenseQueryOptions<GetMetadataMetadataGetQueryResponse, ResponseErrorConfig<Error>, TData, TQueryKey>> & { client?: QueryClient },
  client?: Partial<RequestConfig> & { client?: typeof fetch }
}
 = {}) {
  const { query: queryConfig = {}, client: config = {} } = options ?? {}
  const { client: queryClient, ...queryOptions } = queryConfig
  const queryKey = queryOptions?.queryKey ?? getMetadataMetadataGetSuspenseQueryKey()

  const query = useSuspenseQuery({
   ...getMetadataMetadataGetSuspenseQueryOptions(config),
   queryKey,
   ...queryOptions
  } as unknown as UseSuspenseQueryOptions, queryClient) as UseSuspenseQueryResult<TData, ResponseErrorConfig<Error>> & { queryKey: TQueryKey }

  query.queryKey = queryKey as TQueryKey

  return query
}