/**
* Generated by Kubb (https://kubb.dev/).
* Do not edit manually.
*/

import fetch from "@/lib/authorized-client";
import type { RequestConfig, ResponseErrorConfig } from "@/lib/authorized-client";
import type { QueryKey, QueryClient, QueryObserverOptions, UseQueryResult } from "@tanstack/react-query";
import type { HealthCheckHealthGetQueryResponse } from "../types/HealthCheckHealthGet";
import { queryOptions, useQuery } from "@tanstack/react-query";

export const healthCheckHealthGetQueryKey = () => [{ url: '/health' }] as const

export type HealthCheckHealthGetQueryKey = ReturnType<typeof healthCheckHealthGetQueryKey>

/**
 * @description Check system health status.
 * @summary Health Check
 * {@link /health}
 */
export async function healthCheckHealthGet(config: Partial<RequestConfig> & { client?: typeof fetch } = {}) {
  const { client: request = fetch, ...requestConfig } = config  
  
  const res = await request<HealthCheckHealthGetQueryResponse, ResponseErrorConfig<Error>, unknown>({ method : "GET", url : `/health`, ... requestConfig })  
  return res.data
}

export function healthCheckHealthGetQueryOptions(config: Partial<RequestConfig> & { client?: typeof fetch } = {}) {
  const queryKey = healthCheckHealthGetQueryKey()
  return queryOptions<HealthCheckHealthGetQueryResponse, ResponseErrorConfig<Error>, HealthCheckHealthGetQueryResponse, typeof queryKey>({
 
   queryKey,
   queryFn: async ({ signal }) => {
      config.signal = signal
      return healthCheckHealthGet(config)
   },
  })
}

/**
 * @description Check system health status.
 * @summary Health Check
 * {@link /health}
 */
export function useHealthCheckHealthGet<TData = HealthCheckHealthGetQueryResponse, TQueryData = HealthCheckHealthGetQueryResponse, TQueryKey extends QueryKey = HealthCheckHealthGetQueryKey>(options: 
{
  query?: Partial<QueryObserverOptions<HealthCheckHealthGetQueryResponse, ResponseErrorConfig<Error>, TData, TQueryData, TQueryKey>> & { client?: QueryClient },
  client?: Partial<RequestConfig> & { client?: typeof fetch }
}
 = {}) {
  const { query: queryConfig = {}, client: config = {} } = options ?? {}
  const { client: queryClient, ...queryOptions } = queryConfig
  const queryKey = queryOptions?.queryKey ?? healthCheckHealthGetQueryKey()

  const query = useQuery({
   ...healthCheckHealthGetQueryOptions(config),
   queryKey,
   ...queryOptions
  } as unknown as QueryObserverOptions, queryClient) as UseQueryResult<TData, ResponseErrorConfig<Error>> & { queryKey: TQueryKey }

  query.queryKey = queryKey as TQueryKey

  return query
}