/**
* Generated by Kubb (https://kubb.dev/).
* Do not edit manually.
*/

import fetch from "@/lib/authorized-client";
import type { RequestConfig, ResponseErrorConfig } from "@/lib/authorized-client";
import type { QueryKey, QueryClient, UseSuspenseQueryOptions, UseSuspenseQueryResult } from "@tanstack/react-query";
import type { HealthCheckHealthGetQueryResponse } from "../types/HealthCheckHealthGet";
import { queryOptions, useSuspenseQuery } from "@tanstack/react-query";

export const healthCheckHealthGetSuspenseQueryKey = () => [{ url: '/health' }] as const

export type HealthCheckHealthGetSuspenseQueryKey = ReturnType<typeof healthCheckHealthGetSuspenseQueryKey>

/**
 * @description Check system health status.
 * @summary Health Check
 * {@link /health}
 */
export async function healthCheckHealthGetSuspense(config: Partial<RequestConfig> & { client?: typeof fetch } = {}) {
  const { client: request = fetch, ...requestConfig } = config  
  
  const res = await request<HealthCheckHealthGetQueryResponse, ResponseErrorConfig<Error>, unknown>({ method : "GET", url : `/health`, ... requestConfig })  
  return res.data
}

export function healthCheckHealthGetSuspenseQueryOptions(config: Partial<RequestConfig> & { client?: typeof fetch } = {}) {
  const queryKey = healthCheckHealthGetSuspenseQueryKey()
  return queryOptions<HealthCheckHealthGetQueryResponse, ResponseErrorConfig<Error>, HealthCheckHealthGetQueryResponse, typeof queryKey>({
 
   queryKey,
   queryFn: async ({ signal }) => {
      config.signal = signal
      return healthCheckHealthGetSuspense(config)
   },
  })
}

/**
 * @description Check system health status.
 * @summary Health Check
 * {@link /health}
 */
export function useHealthCheckHealthGetSuspense<TData = HealthCheckHealthGetQueryResponse, TQueryKey extends QueryKey = HealthCheckHealthGetSuspenseQueryKey>(options: 
{
  query?: Partial<UseSuspenseQueryOptions<HealthCheckHealthGetQueryResponse, ResponseErrorConfig<Error>, TData, TQueryKey>> & { client?: QueryClient },
  client?: Partial<RequestConfig> & { client?: typeof fetch }
}
 = {}) {
  const { query: queryConfig = {}, client: config = {} } = options ?? {}
  const { client: queryClient, ...queryOptions } = queryConfig
  const queryKey = queryOptions?.queryKey ?? healthCheckHealthGetSuspenseQueryKey()

  const query = useSuspenseQuery({
   ...healthCheckHealthGetSuspenseQueryOptions(config),
   queryKey,
   ...queryOptions
  } as unknown as UseSuspenseQueryOptions, queryClient) as UseSuspenseQueryResult<TData, ResponseErrorConfig<Error>> & { queryKey: TQueryKey }

  query.queryKey = queryKey as TQueryKey

  return query
}