/**
* Generated by Kubb (https://kubb.dev/).
* Do not edit manually.
*/

import fetch from "@/lib/authorized-client";
import type { RequestConfig, ResponseErrorConfig } from "@/lib/authorized-client";
import type { QueryKey, QueryClient, UseSuspenseQueryOptions, UseSuspenseQueryResult } from "@tanstack/react-query";
import type { MetricsMetricsGetQueryResponse } from "../types/MetricsMetricsGet";
import { queryOptions, useSuspenseQuery } from "@tanstack/react-query";

export const metricsMetricsGetSuspenseQueryKey = () => [{ url: '/metrics' }] as const

export type MetricsMetricsGetSuspenseQueryKey = ReturnType<typeof metricsMetricsGetSuspenseQueryKey>

/**
 * @description Prometheus metrics
 * @summary Metrics
 * {@link /metrics}
 */
export async function metricsMetricsGetSuspense(config: Partial<RequestConfig> & { client?: typeof fetch } = {}) {
  const { client: request = fetch, ...requestConfig } = config  
  
  const res = await request<MetricsMetricsGetQueryResponse, ResponseErrorConfig<Error>, unknown>({ method : "GET", url : `/metrics`, ... requestConfig })  
  return res.data
}

export function metricsMetricsGetSuspenseQueryOptions(config: Partial<RequestConfig> & { client?: typeof fetch } = {}) {
  const queryKey = metricsMetricsGetSuspenseQueryKey()
  return queryOptions<MetricsMetricsGetQueryResponse, ResponseErrorConfig<Error>, MetricsMetricsGetQueryResponse, typeof queryKey>({
 
   queryKey,
   queryFn: async ({ signal }) => {
      config.signal = signal
      return metricsMetricsGetSuspense(config)
   },
  })
}

/**
 * @description Prometheus metrics
 * @summary Metrics
 * {@link /metrics}
 */
export function useMetricsMetricsGetSuspense<TData = MetricsMetricsGetQueryResponse, TQueryKey extends QueryKey = MetricsMetricsGetSuspenseQueryKey>(options: 
{
  query?: Partial<UseSuspenseQueryOptions<MetricsMetricsGetQueryResponse, ResponseErrorConfig<Error>, TData, TQueryKey>> & { client?: QueryClient },
  client?: Partial<RequestConfig> & { client?: typeof fetch }
}
 = {}) {
  const { query: queryConfig = {}, client: config = {} } = options ?? {}
  const { client: queryClient, ...queryOptions } = queryConfig
  const queryKey = queryOptions?.queryKey ?? metricsMetricsGetSuspenseQueryKey()

  const query = useSuspenseQuery({
   ...metricsMetricsGetSuspenseQueryOptions(config),
   queryKey,
   ...queryOptions
  } as unknown as UseSuspenseQueryOptions, queryClient) as UseSuspenseQueryResult<TData, ResponseErrorConfig<Error>> & { queryKey: TQueryKey }

  query.queryKey = queryKey as TQueryKey

  return query
}