/**
* Generated by Kubb (https://kubb.dev/).
* Do not edit manually.
*/

import fetch from "@/lib/authorized-client";
import type { RequestConfig, ResponseErrorConfig } from "@/lib/authorized-client";
import type { QueryKey, QueryClient, QueryObserverOptions, UseQueryResult } from "@tanstack/react-query";
import type { MetricsMetricsGetQueryResponse } from "../types/MetricsMetricsGet";
import { queryOptions, useQuery } from "@tanstack/react-query";

export const metricsMetricsGetQueryKey = () => [{ url: '/metrics' }] as const

export type MetricsMetricsGetQueryKey = ReturnType<typeof metricsMetricsGetQueryKey>

/**
 * @description Prometheus metrics
 * @summary Metrics
 * {@link /metrics}
 */
export async function metricsMetricsGet(config: Partial<RequestConfig> & { client?: typeof fetch } = {}) {
  const { client: request = fetch, ...requestConfig } = config  
  
  const res = await request<MetricsMetricsGetQueryResponse, ResponseErrorConfig<Error>, unknown>({ method : "GET", url : `/metrics`, ... requestConfig })  
  return res.data
}

export function metricsMetricsGetQueryOptions(config: Partial<RequestConfig> & { client?: typeof fetch } = {}) {
  const queryKey = metricsMetricsGetQueryKey()
  return queryOptions<MetricsMetricsGetQueryResponse, ResponseErrorConfig<Error>, MetricsMetricsGetQueryResponse, typeof queryKey>({
 
   queryKey,
   queryFn: async ({ signal }) => {
      config.signal = signal
      return metricsMetricsGet(config)
   },
  })
}

/**
 * @description Prometheus metrics
 * @summary Metrics
 * {@link /metrics}
 */
export function useMetricsMetricsGet<TData = MetricsMetricsGetQueryResponse, TQueryData = MetricsMetricsGetQueryResponse, TQueryKey extends QueryKey = MetricsMetricsGetQueryKey>(options: 
{
  query?: Partial<QueryObserverOptions<MetricsMetricsGetQueryResponse, ResponseErrorConfig<Error>, TData, TQueryData, TQueryKey>> & { client?: QueryClient },
  client?: Partial<RequestConfig> & { client?: typeof fetch }
}
 = {}) {
  const { query: queryConfig = {}, client: config = {} } = options ?? {}
  const { client: queryClient, ...queryOptions } = queryConfig
  const queryKey = queryOptions?.queryKey ?? metricsMetricsGetQueryKey()

  const query = useQuery({
   ...metricsMetricsGetQueryOptions(config),
   queryKey,
   ...queryOptions
  } as unknown as QueryObserverOptions, queryClient) as UseQueryResult<TData, ResponseErrorConfig<Error>> & { queryKey: TQueryKey }

  query.queryKey = queryKey as TQueryKey

  return query
}