/**
* Generated by Kubb (https://kubb.dev/).
* Do not edit manually.
*/

import { z } from "zod";

/**
 * @description A single message in a conversation.
 */
export const chatMessageSchema = z.object({
    "role": z.string().describe("The role of the message sender (e.g. 'user', 'assistant', 'system')."),
"content": z.string().describe("The text content of the message.")
    }).describe("A single message in a conversation.")