/**
* Generated by Kubb (https://kubb.dev/).
* Do not edit manually.
*/

import { chatRequestSchema } from "./chatRequestSchema";
import { chatResponseSchema } from "./chatResponseSchema";
import { HTTPValidationErrorSchema } from "./HTTPValidationErrorSchema";
import { z } from "zod";

export const chatEndpointApiChatPostQueryParamsSchema = z.object({
    "user_id": z.string()
    })

/**
 * @description Successful Response
 */
export const chatEndpointApiChatPost200Schema = z.lazy(() => chatResponseSchema).describe("Response from the local LLM.")

/**
 * @description Validation Error
 */
export const chatEndpointApiChatPost422Schema = z.lazy(() => HTTPValidationErrorSchema)

export const chatEndpointApiChatPostMutationRequestSchema = z.lazy(() => chatRequestSchema).describe("Incoming user chat request.")

export const chatEndpointApiChatPostMutationResponseSchema = z.lazy(() => chatEndpointApiChatPost200Schema)