/**
* Generated by Kubb (https://kubb.dev/).
* Do not edit manually.
*/

import { chatMessageSchema } from "./chatMessageSchema";
import { z } from "zod";

/**
 * @description Incoming user chat request.
 */
export const chatRequestSchema = z.object({
    "messages": z.array(z.lazy(() => chatMessageSchema).describe("A single message in a conversation.")).describe("List of chat messages including roles and contents. Example: [{'role': 'user', 'content': 'Hello!'}]")
    }).describe("Incoming user chat request.")