/**
* Generated by Kubb (https://kubb.dev/).
* Do not edit manually.
*/

import { z } from "zod";

/**
 * @description Response from the local LLM.
 */
export const chatResponseSchema = z.object({
    "response": z.string()
    }).describe("Response from the local LLM.")