/**
* Generated by Kubb (https://kubb.dev/).
* Do not edit manually.
*/

import { z } from "zod";

/**
 * @description Successful Response
 */
export const getConfigApiConfigGet200Schema = z.any()

export const getConfigApiConfigGetQueryResponseSchema = z.lazy(() => getConfigApiConfigGet200Schema)