/**
* Generated by Kubb (https://kubb.dev/).
* Do not edit manually.
*/

import { z } from "zod";

/**
 * @description Successful Response
 */
export const getMetadataMetadataGet200Schema = z.any()

export const getMetadataMetadataGetQueryResponseSchema = z.lazy(() => getMetadataMetadataGet200Schema)