/**
* Generated by Kubb (https://kubb.dev/).
* Do not edit manually.
*/

import { healthResponseSchema } from "./healthResponseSchema";
import { z } from "zod";

/**
 * @description Successful Response
 */
export const healthCheckHealthGet200Schema = z.lazy(() => healthResponseSchema).describe("Health check status.")

export const healthCheckHealthGetQueryResponseSchema = z.lazy(() => healthCheckHealthGet200Schema)