/**
* Generated by Kubb (https://kubb.dev/).
* Do not edit manually.
*/

import { z } from "zod";

/**
 * @description Health check status.
 */
export const healthResponseSchema = z.object({
    "status": z.string()
    }).describe("Health check status.")