/**
* Generated by Kubb (https://kubb.dev/).
* Do not edit manually.
*/

import { validationErrorSchema } from "./validationErrorSchema";
import { z } from "zod";

export const HTTPValidationErrorSchema = z.object({
    "detail": z.array(z.lazy(() => validationErrorSchema)).optional()
    })