/**
* Generated by Kubb (https://kubb.dev/).
* Do not edit manually.
*/

import { z } from "zod";

/**
 * @description Successful Response
 */
export const metricsMetricsGet200Schema = z.any()

export const metricsMetricsGetQueryResponseSchema = z.lazy(() => metricsMetricsGet200Schema)