/**
* Generated by Kubb (https://kubb.dev/).
* Do not edit manually.
*/

import { z } from "zod";

/**
 * @description Response after uploading a PDF file.
 */
export const uploadResponseSchema = z.object({
    "message": z.string()
    }).describe("Response after uploading a PDF file.")