/**
* Generated by Kubb (https://kubb.dev/).
* Do not edit manually.
*/

import { bodyUploadPdfApiUploadPdfPostSchema } from "./bodyUploadPdfApiUploadPdfPostSchema";
import { HTTPValidationErrorSchema } from "./HTTPValidationErrorSchema";
import { uploadResponseSchema } from "./uploadResponseSchema";
import { z } from "zod";

export const uploadPdfApiUploadPdfPostQueryParamsSchema = z.object({
    "user_id": z.string()
    })

/**
 * @description Successful Response
 */
export const uploadPdfApiUploadPdfPost200Schema = z.lazy(() => uploadResponseSchema).describe("Response after uploading a PDF file.")

/**
 * @description Validation Error
 */
export const uploadPdfApiUploadPdfPost422Schema = z.lazy(() => HTTPValidationErrorSchema)

export const uploadPdfApiUploadPdfPostMutationRequestSchema = z.lazy(() => bodyUploadPdfApiUploadPdfPostSchema)

export const uploadPdfApiUploadPdfPostMutationResponseSchema = z.lazy(() => uploadPdfApiUploadPdfPost200Schema)