/**
* Generated by Kubb (https://kubb.dev/).
* Do not edit manually.
*/

import type { ChatRequest } from "./ChatRequest";
import type { ChatResponse } from "./ChatResponse";
import type { HTTPValidationError } from "./HTTPValidationError";

export type ChatEndpointApiChatPostQueryParams = {
    /**
     * @type string
    */
    user_id: string;
};

/**
 * @description Successful Response
*/
export type ChatEndpointApiChatPost200 = ChatResponse;

/**
 * @description Validation Error
*/
export type ChatEndpointApiChatPost422 = HTTPValidationError;

export type ChatEndpointApiChatPostMutationRequest = ChatRequest;

export type ChatEndpointApiChatPostMutationResponse = ChatEndpointApiChatPost200;

export type ChatEndpointApiChatPostMutation = {
    Response: ChatEndpointApiChatPost200;
    Request: ChatEndpointApiChatPostMutationRequest;
    QueryParams: ChatEndpointApiChatPostQueryParams;
    Errors: ChatEndpointApiChatPost422;
};