/**
* Generated by Kubb (https://kubb.dev/).
* Do not edit manually.
*/

import type { ChatMessage } from "./ChatMessage";

/**
 * @description Incoming user chat request.
*/
export type ChatRequest = {
    /**
     * @description List of chat messages including roles and contents. Example: [{\'role\': \'user\', \'content\': \'Hello!\'}]
     * @type array
    */
    messages: ChatMessage[];
};