/**
* Generated by Kubb (https://kubb.dev/).
* Do not edit manually.
*/


/**
 * @description A single message in a conversation.
*/
export type ChatMessage = {
    /**
     * @description The role of the message sender (e.g. \'user\', \'assistant\', \'system\').
     * @type string
    */
    role: string;
    /**
     * @description The text content of the message.
     * @type string
    */
    content: string;
};