/**
* Generated by Kubb (https://kubb.dev/).
* Do not edit manually.
*/


/**
 * @description Response from the local LLM.
*/
export type ChatResponse = {
    /**
     * @type string
    */
    response: string;
};