/**
* Generated by Kubb (https://kubb.dev/).
* Do not edit manually.
*/


/**
 * @description Successful Response
*/
export type GetConfigApiConfigGet200 = any;

export type GetConfigApiConfigGetQueryResponse = GetConfigApiConfigGet200;

export type GetConfigApiConfigGetQuery = {
    Response: GetConfigApiConfigGet200;
    Errors: any;
};