/**
* Generated by Kubb (https://kubb.dev/).
* Do not edit manually.
*/


/**
 * @description Successful Response
*/
export type GetMetadataMetadataGet200 = any;

export type GetMetadataMetadataGetQueryResponse = GetMetadataMetadataGet200;

export type GetMetadataMetadataGetQuery = {
    Response: GetMetadataMetadataGet200;
    Errors: any;
};