/**
* Generated by Kubb (https://kubb.dev/).
* Do not edit manually.
*/

import type { HealthResponse } from "./HealthResponse";

/**
 * @description Successful Response
*/
export type HealthCheckHealthGet200 = HealthResponse;

export type HealthCheckHealthGetQueryResponse = HealthCheckHealthGet200;

export type HealthCheckHealthGetQuery = {
    Response: HealthCheckHealthGet200;
    Errors: any;
};