/**
* Generated by Kubb (https://kubb.dev/).
* Do not edit manually.
*/


/**
 * @description Health check status.
*/
export type HealthResponse = {
    /**
     * @type string
    */
    status: string;
};