/**
* Generated by Kubb (https://kubb.dev/).
* Do not edit manually.
*/


/**
 * @description Successful Response
*/
export type MetricsMetricsGet200 = any;

export type MetricsMetricsGetQueryResponse = MetricsMetricsGet200;

export type MetricsMetricsGetQuery = {
    Response: MetricsMetricsGet200;
    Errors: any;
};