/**
* Generated by Kubb (https://kubb.dev/).
* Do not edit manually.
*/


/**
 * @description Response after uploading a PDF file.
*/
export type UploadResponse = {
    /**
     * @type string
    */
    message: string;
};