/**
* Generated by Kubb (https://kubb.dev/).
* Do not edit manually.
*/

import type { BodyUploadPdfApiUploadPdfPost } from "./BodyUploadPdfApiUploadPdfPost";
import type { HTTPValidationError } from "./HTTPValidationError";
import type { UploadResponse } from "./UploadResponse";

export type UploadPdfApiUploadPdfPostQueryParams = {
    /**
     * @type string
    */
    user_id: string;
};

/**
 * @description Successful Response
*/
export type UploadPdfApiUploadPdfPost200 = UploadResponse;

/**
 * @description Validation Error
*/
export type UploadPdfApiUploadPdfPost422 = HTTPValidationError;

export type UploadPdfApiUploadPdfPostMutationRequest = BodyUploadPdfApiUploadPdfPost;

export type UploadPdfApiUploadPdfPostMutationResponse = UploadPdfApiUploadPdfPost200;

export type UploadPdfApiUploadPdfPostMutation = {
    Response: UploadPdfApiUploadPdfPost200;
    Request: UploadPdfApiUploadPdfPostMutationRequest;
    QueryParams: UploadPdfApiUploadPdfPostQueryParams;
    Errors: UploadPdfApiUploadPdfPost422;
};