/**
* Generated by Kubb (https://kubb.dev/).
* Do not edit manually.
*/

import type { MetricsMetricsGetQueryResponse } from "../types/MetricsMetricsGet";
import { faker } from "@faker-js/faker";

/**
 * @description Successful Response
 */
export function createMetricsMetricsGet200() {
  
  return undefined
}

export function createMetricsMetricsGetQueryResponse(data?: Partial<MetricsMetricsGetQueryResponse>): MetricsMetricsGetQueryResponse {
  
  return data || faker.helpers.arrayElement<any>([createMetricsMetricsGet200()])
}