/**
* Generated by Kubb (https://kubb.dev/).
* Do not edit manually.
*/

import type { ChatRequest } from "../types/ChatRequest";
import { faker } from "@faker-js/faker";
import { createChatMessage } from "./createChatMessage";

/**
 * @description Incoming user chat request.
 */
export function createChatRequest(data?: Partial<ChatRequest>): ChatRequest {
  
  return {
  ...{"messages": faker.helpers.multiple(() => (createChatMessage()))},
  ...data || {}
  }
}