/**
* Generated by Kubb (https://kubb.dev/).
* Do not edit manually.
*/

import type { HTTPValidationError } from "../types/HTTPValidationError";
import { faker } from "@faker-js/faker";
import { createValidationError } from "./createValidationError";

export function createHTTPValidationError(data?: Partial<HTTPValidationError>): HTTPValidationError {
  
  return {
  ...{"detail": faker.helpers.multiple(() => (createValidationError()))},
  ...data || {}
  }
}