/**
* Generated by Kubb (https://kubb.dev/).
* Do not edit manually.
*/

import type { GetMetadataMetadataGetQueryResponse } from "../types/GetMetadataMetadataGet";
import { faker } from "@faker-js/faker";

/**
 * @description Successful Response
 */
export function createGetMetadataMetadataGet200() {
  
  return undefined
}

export function createGetMetadataMetadataGetQueryResponse(data?: Partial<GetMetadataMetadataGetQueryResponse>): GetMetadataMetadataGetQueryResponse {
  
  return data || faker.helpers.arrayElement<any>([createGetMetadataMetadataGet200()])
}