/**
* Generated by Kubb (https://kubb.dev/).
* Do not edit manually.
*/

import type { UploadResponse } from "../types/UploadResponse";
import { faker } from "@faker-js/faker";

/**
 * @description Response after uploading a PDF file.
 */
export function createUploadResponse(data?: Partial<UploadResponse>): UploadResponse {
  
  return {
  ...{"message": faker.string.alpha()},
  ...data || {}
  }
}