/**
* Generated by Kubb (https://kubb.dev/).
* Do not edit manually.
*/

import type { ValidationError } from "../types/ValidationError";
import { faker } from "@faker-js/faker";

export function createValidationError(data?: Partial<ValidationError>): ValidationError {
  
  return {
  ...{"loc": faker.helpers.multiple(() => (faker.helpers.arrayElement<any>([faker.string.alpha(), faker.number.int()]))),"msg": faker.string.alpha(),"type": faker.string.alpha()},
  ...data || {}
  }
}