/**
* Generated by Kubb (https://kubb.dev/).
* Do not edit manually.
*/

import type { HealthCheckHealthGetQueryResponse } from "../types/HealthCheckHealthGet";
import { faker } from "@faker-js/faker";
import { createHealthResponse } from "./createHealthResponse";

/**
 * @description Successful Response
 */
export function createHealthCheckHealthGet200() {
  
  return createHealthResponse()
}

export function createHealthCheckHealthGetQueryResponse(data?: Partial<HealthCheckHealthGetQueryResponse>): HealthCheckHealthGetQueryResponse {
  
  return data || faker.helpers.arrayElement<any>([createHealthCheckHealthGet200()])
}