/**
* Generated by Kubb (https://kubb.dev/).
* Do not edit manually.
*/

import type { BodyUploadPdfApiUploadPdfPost } from "../types/BodyUploadPdfApiUploadPdfPost";
import { faker } from "@faker-js/faker";

export function createBodyUploadPdfApiUploadPdfPost(data?: Partial<BodyUploadPdfApiUploadPdfPost>): BodyUploadPdfApiUploadPdfPost {
  
  return {
  ...{"file": faker.image.url() as unknown as Blob},
  ...data || {}
  }
}