/**
* Generated by Kubb (https://kubb.dev/).
* Do not edit manually.
*/

import type { GetConfigApiConfigGetQueryResponse } from "../types/GetConfigApiConfigGet";
import { faker } from "@faker-js/faker";

/**
 * @description Successful Response
 */
export function createGetConfigApiConfigGet200() {
  
  return undefined
}

export function createGetConfigApiConfigGetQueryResponse(data?: Partial<GetConfigApiConfigGetQueryResponse>): GetConfigApiConfigGetQueryResponse {
  
  return data || faker.helpers.arrayElement<any>([createGetConfigApiConfigGet200()])
}