/**
* Generated by Kubb (https://kubb.dev/).
* Do not edit manually.
*/

import type { ChatEndpointApiChatPostQueryParams, ChatEndpointApiChatPostMutationResponse } from "../types/ChatEndpointApiChatPost";
import { faker } from "@faker-js/faker";
import { createChatRequest } from "./createChatRequest";
import { createChatResponse } from "./createChatResponse";
import { createHTTPValidationError } from "./createHTTPValidationError";

export function createChatEndpointApiChatPostQueryParams(data?: Partial<ChatEndpointApiChatPostQueryParams>): ChatEndpointApiChatPostQueryParams {
  
  return {
  ...{"user_id": faker.string.alpha()},
  ...data || {}
  }
}

/**
 * @description Successful Response
 */
export function createChatEndpointApiChatPost200() {
  
  return createChatResponse()
}

/**
 * @description Validation Error
 */
export function createChatEndpointApiChatPost422() {
  
  return createHTTPValidationError()
}

export function createChatEndpointApiChatPostMutationRequest() {
  
  return createChatRequest()
}

export function createChatEndpointApiChatPostMutationResponse(data?: Partial<ChatEndpointApiChatPostMutationResponse>): ChatEndpointApiChatPostMutationResponse {
  
  return data || faker.helpers.arrayElement<any>([createChatEndpointApiChatPost200()])
}