/**
* Generated by Kubb (https://kubb.dev/).
* Do not edit manually.
*/

import type { ChatMessage } from "../types/ChatMessage";
import { faker } from "@faker-js/faker";

/**
 * @description A single message in a conversation.
 */
export function createChatMessage(data?: Partial<ChatMessage>): ChatMessage {
  
  return {
  ...{"role": faker.string.alpha(),"content": faker.string.alpha()},
  ...data || {}
  }
}