/**
* Generated by Kubb (https://kubb.dev/).
* Do not edit manually.
*/

import type { ChatResponse } from "../types/ChatResponse";
import { faker } from "@faker-js/faker";

/**
 * @description Response from the local LLM.
 */
export function createChatResponse(data?: Partial<ChatResponse>): ChatResponse {
  
  return {
  ...{"response": faker.string.alpha()},
  ...data || {}
  }
}