/**
* Generated by Kubb (https://kubb.dev/).
* Do not edit manually.
*/

import type { HealthResponse } from "../types/HealthResponse";
import { faker } from "@faker-js/faker";

/**
 * @description Health check status.
 */
export function createHealthResponse(data?: Partial<HealthResponse>): HealthResponse {
  
  return {
  ...{"status": faker.string.alpha()},
  ...data || {}
  }
}